import { CategoryMetadataRecord } from "../types/CategoryMetadata";

const categoryMetadata: CategoryMetadataRecord = {
  colors: [
    { key: "red", hex: "#ef4444", label: "Red" },
    { key: "orange", hex: "#f97316", label: "Orange" },
    { key: "yellow", hex: "#eab308", label: "Yellow" },
    { key: "green", hex: "#22c55e", label: "Green" },
    { key: "cyan", hex: "#06b6d4", label: "Cyan" },
    { key: "blue", hex: "#3b82f6", label: "Blue" },
    { key: "violet", hex: "#8b5cf6", label: "Violet" },
    { key: "pink", hex: "#ec4899", label: "Pink" },
    { key: "amber", hex: "#f59e0b", label: "Amber" },
    { key: "emerald", hex: "#10b981", label: "Emerald" },
    { key: "teal", hex: "#14b8a6", label: "Teal" },
    { key: "indigo", hex: "#6366f1", label: "Indigo" },
    { key: "purple", hex: "#a855f7", label: "Purple" },
    { key: "rose", hex: "#f43f5e", label: "Rose" },
    { key: "lime", hex: "#84cc16", label: "Lime" },
    { key: "sky", hex: "#06b6d4", label: "Sky" },
    { key: "pink-2", hex: "#f472b6", label: "Pink" },
    { key: "violet-2", hex: "#a78bfa", label: "Violet" },
    { key: "emerald-2", hex: "#34d399", label: "Emerald" },
    { key: "amber-2", hex: "#fbbf24", label: "Amber" },
  ],
  icons: [
    { keyword: 'food', icon: '🍕', label: 'Food' },
    { keyword: 'transport', icon: '🚗', label: 'Transport' },
    { keyword: 'shopping', icon: '🛍️', label: 'Shopping' },
    { keyword: 'entertainment', icon: '🎬', label: 'Entertainment' },
    { keyword: 'health', icon: '🏥', label: 'Health' },
    { keyword: 'education', icon: '📚', label: 'Education' },
    { keyword: 'home', icon: '🏠', label: 'Home' },
    { keyword: 'work', icon: '💼', label: 'Work' },
    { keyword: 'travel', icon: '✈️', label: 'Travel' },
    { keyword: 'bills', icon: '📄', label: 'Bills' },
    { keyword: 'utilities', icon: '⚡', label: 'Utilities' },
    { keyword: 'insurance', icon: '🛡️', label: 'Insurance' },
    { keyword: 'gifts', icon: '🎁', label: 'Gifts' },
    { keyword: 'sports', icon: '⚽', label: 'Sports' },
    { keyword: 'technology', icon: '💻', label: 'Technology' },
    { keyword: 'beauty', icon: '💄', label: 'Beauty' },
    { keyword: 'pets', icon: '🐕', label: 'Pets' },
    { keyword: 'coffee', icon: '☕', label: 'Coffee' },
    { keyword: 'alcohol', icon: '🍺', label: 'Alcohol' },
    { keyword: 'other', icon: '📌', label: 'Other' },
  ],
};

export default categoryMetadata;
